### ISSUE TITLE
Inserting a link?

### ISSUE THREAD

**Issue by saurabhsharan** [matthewsot/docs-plus#3]
Super cool library - thanks for making it open source!

I want to programmatically insert a link into a google doc. So far, I've tried to modify `docs.pasteText` to change the type and data to something like:

```
data.setData("text/html", '<a href="www.google.com">Google</a>');
````

but it doesn't seem to work. I also tried to simulate pressing Cmd-K (the default keyboard shortcut for inserting a link), but that also doesn't seem to work.

Is there any other way to insert a link? I'm hopeful since it seems like that's what's happening in this screenshot here: https://github.com/matthewsot/docs-plus/blob/master/screenshots/actionselector.jpg :)

**Comment by matthewsot** [comment]
Hello! Thanks for reaching out, glad you like the library.

Unfortunately, it doesn't currently support pasting links. What you tried sounds reasonable, but I guess that's not how they get links.

The screenshot you linked isn't actually adding a link, it just writes, e.g., 'Everyone' into the document at that point (the add-on would then parse the document looking for such @Everyone text snippets).

Here are two things you could try:

#### Fake Mouse Clicks
Try to fake a mouse click on the "Insert -> Link" menu item, like we do with undo/redo here: https://github.com/matthewsot/docs-plus/commit/e8ffe5e7bb1a9983a39eac21389867dd1aa0cbfe#diff-804e9311ee8c5dccf326dd0d59b46728R165-R168

That should at least open up the 'insert link' popup. You may need a timeout or a DOM watcher to know when it opens, as it seems it takes a second for the popup to show up. Once it opens you should be able to edit those two input form fields directly and press the 'Apply' button.

#### Fake Key Clicks
You can try something like `docs.pasteText("https://google.com/ ")` (note the space at the end), which _should_ hopefully create the link in the doc. Then you can use the selection helpers to select, say, `ttps://google.com` and type over it with `Google`. That should result in a link `hGoogle/`. You can then try to navigate back and delete the leading `h` and trailing `/`. It would look something like this pseudocode:
```
link, text = from user
paste(link + " ")
for i = 1, 2, ... (len(link) - 1):
    pressLeftArrow()
paste(text)
for i = 1, 2, ... (len(link) - 1):
    pressDeleteKey()
for i = 1, 2, ... len(text):
    pressLeftArrow()
pressBackspace()
```
The drawback to this approach is that you might run into some hard-to-debug timing issues, or complications if the text is more complicated than just 'Google.' But I think it might work.

**Comment by matthewsot** [comment]
Actually, you might have to do them in separate steps:
```
paste(link)
pressKey(' ')
```
If you get something working feel free to send a PR! I'll also try to take a closer look at it sometime.

**Comment by matthewsot** [comment]
The fake mouse clicks approach worked. Please see #4 and let me know if it works for you.

**Comment by matthewsot** [comment]
Merged. Feel free to re-open if it doesn't work.
